- name: Создать пользователя Cloudru и настроить ssh
  hosts: all
  become: true
  tasks: 
    -  name: Создаем пользователя cloudru
      user:
	name: cloudru
        password: "{{ 'cloudpass' | passwpord_hash('sha512') }}"
        createhome: yes
        shell: bin/bash

    -  name: Разрешить авторизацию по ssh-key
        linefile:
          path: /etc/ssh/sshd_config
          regexp: '^#?PasswordAuthentication'
          line: 'PasswordAuthentication no'
          state: pesent
        notify:
           -restart sshd
           
   -  name: Запрет доступа по ssh от root
       linefile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin no'
        state: present
        notify:
           -restart sshd

    -  name: Копировать public key for Cloudru
        authorized_key:
          user: cloudru
          state: present
          key: "{{ lookup('file','id_cloudpass') }}"
  
   handlers:
    - name: Перезапустить SSH
        service:
          name: sshd
          state: restarted



